# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-03 11:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PythonSubTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_title', models.CharField(max_length=30, verbose_name='\u5b50\u7ae0\u8282\u540d\u79f0')),
                ('detail', models.CharField(max_length=3000, verbose_name='\u8be6\u60c5')),
            ],
        ),
        migrations.CreateModel(
            name='PythonTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='\u7ae0\u8282\u540d\u79f0')),
            ],
        ),
        migrations.AddField(
            model_name='pythonsubtitle',
            name='python_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='python_sub_title', to='blog_2.PythonTitle'),
        ),
    ]
