# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-24 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_2', '0003_auto_20171224_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('1', '\u7537'), ('2', '\u5973')], default='1', max_length=4),
        ),
    ]
